### ISSUE TITLE
Assigning positive damages to structures with basements with less -4 ft flooding.

### ISSUE THREAD

**Issue by plrvn** [nhrap-dev/FAST#1]
For SOID = R12B, although depth is less than -4 ft, the program is assigning 4% of damage to these structures.

**Comment by ujvalak** [comment]
Hello Paul,
We tried to replicate this with the HI and ND data packaged with the tool but did not see it. This is functionality as designed. Please see attached image for the look up DDF for building structure.
Thanks
![DDF_BuildingStructure_depth4ft](https://user-images.githubusercontent.com/10346175/70758524-30896800-1cf8-11ea-8994-7cb667fb635f.jpg)

**Comment by ujvalak** [comment]
Do you mind sending us your dataset via a shared link if you used FAST on a dataset other than the default ones provided?

Thanks

**Comment by plrvn** [comment]
Thank you for looking into this. I would be happy to share my dataset. I tracked down the issue to cases where the Depth Grid is positive, but the Depth in Structure is less than -4 feet and in certain cases can be very negative, yet positive damages are still assigned. I think this is more often than not coming from errors in the first floor elevation or the depth raster.

**Comment by ujvalak** [comment]
Yes, please send us your dataset and we will try to look into it further. Thanks!
