### ISSUE TITLE
index 193466 is out of bounds for axis 0 with size 11302

### ISSUE THREAD

**Issue by rbinmo1** [nhrap-dev/FAST#5]
I tried to run Hazus_FAST a few time but it failed. In the log file its showing "index 193466 is out of bounds for axis 0 with size 11302". How can i solve the problem?

Thanks,
Rubay

**Comment by ujvalak** [comment]
What is the size and projection of your raster?

**Comment by ujvalak** [comment]
I just noticed that you are using the development version of FAST. Can you please download FAST  from  here: https://github.com/nhrap-hazus/FAST.  This is the latest version.

**Comment by rbinmo1** [comment]
> 
> 
> What is the size and projection of your raster?

![image](https://user-images.githubusercontent.com/63298255/82406600-aa064e80-9a2c-11ea-9a71-50266aa25d81.png)
![image](https://user-images.githubusercontent.com/63298255/82406640-c86c4a00-9a2c-11ea-831c-77ea8ba7ee39.png)

**Comment by rbinmo1** [comment]
> 
> 
> I just noticed that you are using the development version of FAST. Can you please download FAST from here: https://github.com/nhrap-hazus/FAST. This is the latest version.

![image](https://user-images.githubusercontent.com/63298255/82406789-24cf6980-9a2d-11ea-97e2-84b204459a96.png)
I downloaded the latest version from your provided link. but it have the same problem.

**Comment by ujvalak** [comment]
Please change the projection to WGS84.

**Comment by ujvalak** [comment]
Please use the pdfs under the Help folder to prep your site-specific data before using it as an input to FAST

**Comment by ujvalak** [comment]
Please check if all your points are within the depth grid extents. Thanks
