### ISSUE TITLE
Result file attribute details

### ISSUE THREAD

**Issue by rbinmo1** [nhrap-dev/FAST#6]
Could you please share the attribute (field/column) details of the final output files?

Thanks,
Rubay

**Comment by ujvalak** [comment]
Hi Rubay,

Here are fields generated as results of the FAST run.

BldgLossUSD
ContentLossUSD
InventoryLossUSD
Debris_Fin
Debris_Struc
Debris_Found
Debris_Tot
Restor_Days_Min
Restor_Days_Max

Thanks
Ujvala
